name: curbshop_mobile_customer
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Formatting
  intl: ^0.17.0

  # Style & Design
  sliding_up_panel: ^1.0.2
  google_fonts: ^2.0.0
  flutter_icons: ^1.1.0

  # Firebase
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  google_sign_in: ^5.0.1

  #Backend

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/illustrations/
